feat(package): `parse-dont-validate`
moltar/typescript-runtime-type-benchmarks pull request #1008
Opened 2022-10-24 05:33 UTC by GervinFung

This PR is to address the issue of #1007

2022-10-24 06:40 UTC, moltar requested changes
Also looks like this adds a yarn lock.

2022-10-24 06:40 UTC, moltar commented on package.json
> +    "parse-dont-validate": "^4.0.0",
Please use pinned version

2022-10-24 08:46 UTC, GervinFung commented on package.json
> +    "parse-dont-validate": "^4.0.0",
Sure

2022-10-24 08:47 UTC, GervinFung commented
> Also looks like this adds a yarn lock.

Ops my bad

2022-10-24 09:16 UTC, moltar commented
There's a test failure:

> all cases must have been imported in tests

```
  Expected: 34
    Received: 35

      48 |   });
      49 |
    > 50 |   expect(registeredCases.size).toEqual(cases.length);
         |                                ^
      51 | });
      52 |
      53 | getRegisteredBenchmarks().forEach(([benchmarkId, benchmarkCases]) => {

```

2022-10-24 11:51 UTC, GervinFung commented
> There's a test failure:
> 
> > all cases must have been imported in tests
> 
> ```
>   Expected: 34
>     Received: 35
> 
>       48 |   });
>       49 |
>     > 50 |   expect(registeredCases.size).toEqual(cases.length);
>          |                                ^
>       51 | });
>       52 |
>       53 | getRegisteredBenchmarks().forEach(([benchmarkId, benchmarkCases]) => {
> ```

Oh no, must have forgotten to run the test, will fix it ASAP

2022-10-25 20:05 UTC, merged

2022-10-26 00:25 UTC, GervinFung commented
> Thanks, @GervinFung for applying the fixes. Looks good.
> 
> Also, check your email, I sent you one a few days ago.

Thanks for merging it! Yeah I will check my email
Also, I saw the benchmark failed