Add Deepkit
moltar/typescript-runtime-type-benchmarks pull request #1199
Opened 2024-01-30 20:36 UTC by M-jerez

Hi @moltar,  First of all thanks for this repo, I'm sure is becoming a reference with everything validation related in JS/Typescript! 👍

This PR adds the Deepkit validation library `@deepkit/types` to the benchmarks.  https://deepkit.io/

Any questions or ammends please let me know!

2024-01-30 20:39 UTC, moltar requested changes

2024-01-30 20:39 UTC, moltar commented on package.json
> +    "@deepkit/type-compiler": "^1.0.1-alpha.117",
Please pin deps to exact versions.

2024-01-30 20:40 UTC, moltar commented
Also, please run a linter `npm run lint`. Thanks!

2024-01-30 22:03 UTC, M-jerez commented
@moltar all fixes applied, linting and testing passing in local.
I also did review the test so it better reflect deepkit's capabilities. 

Think everything should be ready to go 👍

2024-01-31 10:50 UTC, M-jerez commented
@moltar  quick question about these conflicts with the test results `docs/results/node-20.json`. 
Should I remove my changes so there are no more conflicts (I guess there is an action to run the benchmark in this case) or should i keep overriding the result from main with mine to include the deepkit results?

2024-01-31 11:01 UTC, moltar commented
> @moltar quick question about these conflicts with the test results `docs/results/node-20.json`. Should I remove my changes so there are no more conflicts (I guess there is an action to run the benchmark in this case) or should i keep overriding the result from main with mine to include the deepkit results?

Hey, yes, the tests will be auto-generated by CI, so it is safe to remove the file and that would fix the conflict.

2024-01-31 21:03 UTC, moltar approved these changes

2024-01-31 21:16 UTC, merged