added ok-computer
moltar/typescript-runtime-type-benchmarks pull request #865
Opened 2022-05-17 08:21 UTC by richardscarrott

https://github.com/moltar/typescript-runtime-type-benchmarks/issues/696

2022-05-17 08:43 UTC, richardscarrott commented
Not sure why ok-computer is so slow as, although I haven't / don't intent to make micro optimisations, it's running a few orders of magnitude slower than others; I'll push a new version once I've done some optimisation.

2022-05-17 17:03 UTC, moltar commented
@richardscarrott See #864, which might affect the benchmarks.

@hoeck has a PR for this in #866, which will get out soon, so might want to wait for that and retry your benchmarks.

Cheers and thanks for this PR!

2022-05-17 17:05 UTC, moltar requested changes
One small change though. We pin the exact version to make sure that we record the bench results against the exact version.

2022-05-17 17:05 UTC, moltar commented on package.json
> +    "ok-computer": "^1.0.0",
```suggestion
    "ok-computer": "1.0.0",
```

2022-05-17 17:06 UTC, moltar commented on package-lock.json
> +        "ok-computer": "^1.0.0",
```suggestion
        "ok-computer": "1.0.0",
```

2022-05-17 17:10 UTC, moltar approved these changes

2022-05-17 17:10 UTC, merged

2022-05-18 08:38 UTC, richardscarrott commented
@moltar I did some profiling this morning and found it was genuinely slower than it should have been due to hitting a catch block frequently. I made a fix here https://github.com/richardscarrott/ok-computer/pull/7 and sent an update to the benchmarks here https://github.com/moltar/typescript-runtime-type-benchmarks/pull/869

2022-05-18 09:55 UTC, moltar commented
Awesome!!