benchmark each module in their own node process
moltar/typescript-runtime-type-benchmarks pull request #866
Opened 2022-05-17 13:41 UTC by hoeck

trying to fix #864

2022-05-17 17:00 UTC, moltar requested changes
Some lint issues but otherwise great work!

2022-05-17 17:00 UTC, moltar commented on index.ts
> +      process.exit(1);
> Don't use process.exit(); throw an error instead

eslint-ignore it?

2022-05-17 17:00 UTC, moltar commented on test/benchmarks.test.ts
> +  getRegisteredBenchmarks().forEach(([benchmarkId, benchmarkCases]) => {
> 'benchmarkId' is defined but never used

2022-05-17 17:07 UTC, tonivj5 commented
Very excited to see the "real" ones result 👀👏🏻

2022-05-17 17:11 UTC, moltar commented
Oops, sorry, I've introduced a small conflict by merging #865

2022-05-22 17:54 UTC, hoeck commented
@moltar fixed all linter issues (atm. I am not using Eslint at work so I always forget about it on other projects :sweat_smile:)

Rebased, added a message linking to this issue and disabled an Eslint rule that was complaining about the way spectypes are imported.

2022-05-22 18:02 UTC, hoeck commented
Sorry for the noise, I should have used a Github markdown previewer :expressionless: :grinning:.

2022-05-23 15:09 UTC, moltar approved these changes

2022-05-23 15:10 UTC, merged

2022-05-23 15:10 UTC, moltar commented
Sweet @hoeck! 

> I am not using Eslint at work 

Do you use something else?

2022-05-24 03:03 UTC, sinclairzx81 commented
@hoeck Good work :) +1

2022-05-24 05:37 UTC, hoeck commented
> Do you use something else?

No, we're only using prettier in our team of two. There have been always more important tasks than fixing the old and ignored tslint setup :smile: .