feat: add @sapphire/shapeshift
moltar/typescript-runtime-type-benchmarks pull request #934
Opened 2022-07-25 04:23 UTC by imranbarbhuiya

2022-07-25 04:52 UTC, moltar requested changes

2022-07-25 04:52 UTC, moltar commented on package.json
> +    "@sapphire/shapeshift": "^3.5.1",
Use fixed versions, please.

2022-07-25 15:40 UTC, moltar commented
✅ LGTM!

2022-07-25 15:40 UTC, moltar approved these changes

2022-07-26 11:56 UTC, hoeck approved these changes

2022-07-26 12:02 UTC, merged